- framework/call.go
- framework/gnokey.go
This PR has two commits. The first commit adds call.go which copies the private structs and functions from https://github.com/gnolang/gno/blob/master/tm2/pkg/crypto/keys/client/call.go and dependencies. This makes small changes so that we don't need the console I/O.
The second commit updates the Hello function to call `execCall` to add a reply to the message board at testnet.gno.berty.io . This has lots of hard-wired accounts and values, so it is only a demonstration test. We will make it more general.
> chore: Add execCall and test it from Hello

- framework/call.go
- framework/gnokey.go
- gnoboard/android/app/src/main/java/land/gno/gnoboard/MainApplication.java
- gnoboard/android/app/src/main/java/land/gno/gobridge/GoBridgeModule.java
- gnoboard/android/app/src/main/java/land/gno/rootdir/RootDirModule.java
- gnoboard/android/app/src/main/java/land/gno/rootdir/RootDirPackage.java
- gnoboard/ios/Sources/RootDir/RootDir.m
- gnoboard/ios/Sources/RootDir/RootDir.swift
- gnoboard/ios/gnoboard.xcodeproj/project.pbxproj
- gnoboard/ios/gnoboard/Sources/Bridge/GoBridge.swift
- go.mod
- go.sum
This PR fixes a crash when I try to run the gnoboard app on Android and on some iOS devices.
The Gno configuration struct `BaseOptions` needs a `dataDir` path to create files. The default `HomeDir()` function provided in `tm2/pkg/crypto/keys/client/common.go` to get that path doesn't work on mobile and causes a `panic`, because some environment variables are not set on mobile.
The `HomeDir` function is called every time the `tm2/pkg/crypto/keys/client` subfolder is imported because of the global variable `DefaultBaseOptions` that calls `Homedir`. To avoid the call of the `HomeDir` function that calls a `panic`, we duplicated `BaseOptions` in **gnomobile**, so the  `tm2/pkg/crypto/keys/client` is no more imported and we provided it the app container path directory from the Android/iOS …
> Fix: get app dir from native part to initialize Gno's structures

- framework/gnokey.go
In PR #7, the `Hello` function now takes the correct `rootDir` on the mobile storage. This is used to create the KeyBase which now persists even if the app is upgraded. This PR updates the `Hello` function to only create the account if the KeyBase is empty, using the hard-wired account. (This is only for PoC and will be improved with correct account management.)
> In Hello, use the existing account in KeyBase if present

- README.md
The README currently says `git clone git@github.com:gnolang/gnomobile.git`. But the `git@` protocol requires the user to be logged in to GitHub (or have keys set up on the platform). This makes testing on new platforms difficult. This pull request changes to clone with the https protocol which does not require a user account.
> chore: In README, clone with https, not git protocol

- gnoboard/android/app/src/main/java/land/gno/gobridge/GoBridgeModule.java
- gnoboard/android/app/src/main/java/land/gno/rootdir/RootDirModule.java
- gnoboard/ios/Podfile.lock
- gnoboard/ios/gnoboard/Sources/Bridge/GoBridge.m
- gnoboard/ios/gnoboard/Sources/Bridge/GoBridge.swift
- gnoboard/src/native_modules/GoBridge.ts
- gnoboard/src/native_modules/GoBridgeInterface.ts
- gnoboard/src/screens/home/index.tsx
- gnoboard/src/utils/bridge.ts
- service/api.go
In the meantime we implement a TS gRPC client, we expose three methods to manage accounts:
- listKeyInfo
- createAccount
- selectAccount
So the frontend team can continue to work on these functionalities.
> feat: export listKeyInfo, createAccount and selectAccount to RN

- framework/bridge.go
- service/service.go
Similar to libp2p Config, define service.Config and use it to initialize gnomobileService. Rename WithTcpListener to WithUseTcpListener for consistency with BridgeConfig.
> chore: Add service.Config used by gnomobileService

- service/api.go
ListKeyInfo maps the key list into an array of Protobuf KeyInfo . We need to initialize `formatedKeys` as zero length, then append as we map the values (if any).
> fix: In ListKeyInfo, initialize formatedKeys as zero length, then apppend

- service/api.go
- service/service.go
This PR resolves issue #29. This PR allows the user to remember the account password during the runtime. It's not about storing the password in the OS password manager to recover it later between two app runs.
> Chore: Remember the password in the gnomobileService

- gnoboard/.storybook/storybook.requires.js
- gnoboard/src/components/buttons/index.tsx
- gnoboard/src/components/common/side-menu-account-item/side-menu-account-item.tsx
- gnoboard/src/components/modal/Modal.stories.tsx
- gnoboard/src/components/modal/ModalConfirm.stories.tsx
- gnoboard/src/components/modal/ModalConfirm.tsx
- gnoboard/src/components/modal/ModalHeader.tsx
- gnoboard/src/components/modal/index.ts
- gnoboard/src/components/row/Ruller.tsx
- gnoboard/src/components/row/index.tsx
- gnoboard/src/components/texts/index.ts
- gnoboard/src/screens/certify/create-password/index.tsx
- gnoboard/src/screens/certify/your-seed-phrase/index.tsx
- gnoboard/src/screens/devmode/index.tsx
- gnoboard/src/screens/remove-account/confirm.tsx
- gnoboard/src/screens/wallet/home/index.tsx
- gnoboard/src/styles/colors.ts
- This PR adds a new modal component and its styles. It will be used in the next PR to solve [#30](https://github.com/gnolang/gnomobile/issues/30)
- It also creates a new set pre-defined styles for buttons: `'primary' | 'secondary' | 'tertiary' | 'white' | 'primary2' | 'primary-red' | 'secondary-red'` [here](https://github.com/gnolang/gnomobile/pull/62/files#diff-4a0bd3030998ab6f0a58cb6ea42349bcf452ddbe193839414aa98ecb278e8e32R8)
src="https://github.com/gnolang/gnomobile/assets/689440/75453b28-c395-47c9-ae9f-96adca1be5e9" />
> feat: modal component

- gen.sum
- gnoboard/src/api/rpc_connect.d.ts
- gnoboard/src/api/rpc_connect.js
- gnoclient/signer.go
- service/api.go
- service/rpc/rpc.proto
- service/rpc/rpcconnect/rpc.connect.go
As we discussed, this PR supports validating the password as follows:
* In the gnoclient Signer `Validate` function, verify if the password unlocks the account by signing a blank transaction.
* In the gRPC `SetPassword` function, call `Validate` and return `ErrDecryptionFailed` if the password is invalid.
* In the gRPC Protobuf api, update the doc comment for `SetPassword`.
> chore: In SetPassword, validate the password

- gnoboard/src/api/error.ts
- gnoboard/src/screens/devmode/index.tsx
- gnoboard/src/screens/wallet/home/index.tsx
- go.mod
- go.sum
- service/api.go
- service/rpc/error.go
The ConnectError object has a Details field that allows us to add our API error type next to the GRPC error (see [doc](https://connectrpc.com/docs/go/errors#error-details)).
In Go, before returning an API's type error, we have to encapsulate it in the ConnectError object, with the `.grpc()` method.
To handle the error correctly in React-Native, I added a GRPCError class. We can get the API's error code with the `.errCode()` method.
> feat: Use the Buf's ConnectError to throw errors to React-Native

- gnoboard/src/hooks/use-gno.ts
In use-gno.ts, the helper method `call` creates a CallRequest which also has fields `send` and `memo`. We have not used these so far, but this PR adds them as params to `call`. These are optional final arguments, so this is backwards compatible with existing code.
> chore: In use-gno.ts call, add params send and memo

- gnoboard/src/hooks/use-gno.ts
- service/config.go
The doc for SetRemote says that the [default is 127.0.0.1](https://github.com/gnolang/gnomobile/blob/aaddabcb7a789b8f209afc83cddccac3d431893a/service/rpc/rpc.proto#L13) . This makes sense because the toolkit shouldn't be hardwired to a particular remote like the Berty testnet. However, at the moment, the gRPC service initializes the remote to the Berty testnet. But now the example app shows how to call SetRemote to change the network, so we don't need to be hardwired to the Berty testnet.
This PR changes the gRPC service so that the default remote is 127.0.0.1 . The useGno function is changed to set the remote to the Berty testnet for use by the app. (If the app is configured for a different default network, then this is where we can set it.)
> chore: Set the default remote to 127.0.0.1. In useGno, initialize to testnet.gno.berty.io

- README.md
Add instructions for optionally installing Android studio (taken from [gomobile-ipfs](https://github.com/ipfs-shipyard/gomobile-ipfs/blob/master/INSTALL.md)). Also, if not building for iOS, say to edit `.tool-versions` and remove ruby and cocoapods, which don't work on Ubuntu.
> chore: In README, clarify installing prerequisites including Android Studio

- README.md
We renamed the project from GnoMobile to Gno Native Kit, and renamed the repo from gnolang/gnomobile to gnolang/gnonative . This is a quick update to the README to use the new name. We can update the internal go package names and the README project description in a later PR.
> chore: In the README, rename gnomobile to Gno Native Kit or gnonative

- goserver/main.go
I assume this was a copy/paste error, copying from goclient.
> fix: In goserver, fix help typo: goclient should be goserver

- go.mod
- go.sum
- service/api.go
A [recent PR](https://github.com/gnolang/gno/pull/1565) updates the [gnoclient `Call` method](https://github.com/gnolang/gno/pull/1565/files#diff-752f791213b77833b3df087a07a123d4a03f522436c96b03e5e57aa2461e18f8). So we need to update gnonative to use it.
This PR updates go.mod to use the latest gnolang/gno, and updates gnoNativeService `Call` to use the new format.
> chore: Update gnoNativeService Call to the new gnoclient API

- templates/es/use-gno-web.ts
PR #114 updated `call` to use `MsgCall`. This included all the "use-gno" files, but I missed one. This PR updates `call` in use-gno-web to use `MsgCall`, like [in use-gno](https://github.com/gnolang/gnonative/pull/114/files#diff-7abed41c7fed8c0f475e3e64482f4037fba5233053f90278a09cc4a6f78610bb).
> fix: In use-gno-web call, need to use MsgCall like in use-gno

- service/api.go
When calling `QueryAccount` on a blockchain, the response `PubKey` can be nil if there is only a coin transaction for the account address. The problem is that the conversion code in api.go expects a non-nil value. For example, in the gnoboard app with the Portal Loop remote node, `QueryAccount` for the test1 account address throws the error "Thread 11: EXC_BAD_ACCESS (code=1, address=0x20)" for the [code here](https://github.com/gnolang/gnonative/blob/8d48ee0f612be5b465eda993214fcfdfa89563d5/service/api.go#L278).
This PR, checks if the response `PubKey` is nil.
> fix: In QueryAccount, allow nil PubKey

- README.md
The gnoboard folder was moved when we created the examples folder. Update the README. Resolves issue #118.
> chore: In README, update the gnoboard folder location

- examples/js/react-native/gnoboard/src/resources/chains/chains.json
A [recent commit](https://github.com/gnolang/gno/blame/01e91be7bbde8e9cfc2069f66f24bc83d677103a/contribs/gnodev/main.go#L54) updates gnodev to use the chain ID "dev". When gnodev is updated locally or on the Berty test node, it needs to use this chain ID. So, this PR renames "tendermint_test" to "dev".
> chore: Rename chain ID tendermint_test to dev

- README.md
- docs/getting-started/create-new-app.md
Now, `make new-app` is working, so update the instructions to use it. We also update the main README to remove support for macOS 12, which reaches end of life this year (and has compile problems).
> fix: Update create-new-app.md instructions for new-app

- .tool-versions
- README.md
It seems that asdf doesn't support jq on some platforms. (We've had trouble with macOS M1, both laptops and virtual machines.) This PR removes jq from .tool-versions and updates the README to install it with brew.
> chore: Install jq with brew (not asdf)

- .github/workflows/release.yml
- .releaserc
- .releaserc.js
- Makefile
- expo/Makefile
- expo/README.md
- expo/example/App.tsx
- expo/example/metro.config.js
- expo/example/tsconfig.json
- expo/example/webpack.config.js
- expo/package-lock.json
- expo/package.json
This PR should fix the semantic release CI Job, but we also have to set up the NPM_TOKEN secret in the repo to get it working.
We split some rules in the main Makefile to be able to compile only the Go framework without other unnecessary stuff.
> fix: release CI job

- expo/README.md
fix a typo: `avalaible`->`available`
> chore: fix typos

- expo/README.md
- expo/example/App.tsx
- expo/src/hooks/use-gno.ts
- expo/src/index.ts
- expo/src/provider/gnokey-provider.tsx
This pull request fixes an issue with multiple initializations and adds a new component called GnokeyProvider. The GnokeyProvider component allows for the initialization and management of Gnokey.
> Fix initialization issue by adding GnokeyProvider

- expo/example/App.tsx
- expo/src/index.ts
- expo/src/provider/gnonative-provider.tsx
This pull request renames the React Context Provider from GnokeyProvider to GnoNativeProvider. The changes include updating the import statements, renaming the component, and updating the references throughout the codebase. This change improves the clarity and consistency of the codebase.
> refactor: Rename the React Context Provider to GnoNativeProvider

- README.md
Ubuntu 24.04 has been released. Also, the latest Android Studio is Jellyfish. I tested the README instructions in fresh Ubuntu and macOS virtual machines.
* Include Ubuntu 24.04 in the supported versions
* Remove Ubuntu 18.04 which is past end-of-life
* Change to the latest tested Android Studio, Jellyfish
* Ubuntu 24.04 doesn't come with `make`, so add it to the install list
> chore: In README, change to Jellyfish, add Ubuntu 24.04

- framework/service/bridge.go
Using localhost:0 make the OS select an available port. Fixes #142
Tested on Android and iOS simulators, able to launch both gnoboard and dSocial (which both create their own GnoNative gRPC server).
> chore: In NewBridge, for UseTcpListener, use addr localhost:0

- .github/workflows/release.yml
Sometime the Semantic Release CI job timeouts, maybe to dependancies download. So we want to increase the timeout to avoid that.
> fix: increase the semantic release CI job that timeout sometime

- expo/.npmignore
The NPM package reached the size limit so we decided to remove a duplicate Framework in the iOS version.
> fix: ignore simulator iOS Framework to save space

- expo/android/src/main/java/land/gno/gnonative/GnonativeModule.kt
In the expo `GnonativeModule` for iOS, we already handle the `OnDestroy` event. For consistency, this PR updates Android to also handle the `OnDestroy` event.
Note: In my testing, I have not been able to get the app to invoke the `OnDestroy` event, on Android or iOS. On Android, I am able to get the app to invoke the `OnActivityDestroys` event, but this is for an activity, not the module (and is not symmetric with the module `OnCreate`).
> chore: In expo GnonativeModule for Android, handle event OnDestroy

- goserver/main.go
This is the node for dSocial. It is more reliable as a test node.
> chore: In goserver, use the Berty node api.gno.berty.io

- service/api.go
The file structure was changed in PR https://github.com/gnolang/gnonative/pull/92 . This PR is a followup to fix the file location in the doc comment for api.go .
> chore: In api.go, fix doc comment for file locations

- expo/android/src/main/java/land/gno/gnonative/GoBridgeError.kt
- expo/android/src/main/java/land/gno/gnonative/JavaPromiseBlock.kt
- expo/src/grpc/error.ts
- expo/src/index.ts
Expose ErrCode class and add rpc_pb to exports.
Useful for client who wants to implements error checks on their dApps, eg:
```
import { ErrCode } from "@gnolang/gnonative";  
if (err.errCode() === ErrCode.ErrDecryptionFailed) {
setError("Wrong password, please try again.");
}
```
> chore: exposing ErrCode class

- service/api.go
- service/service.go
The Gnokey Mobile service has a pointer to the local Gno Native Kit service so that it can perform functions with direct Go calls. This PR updates `GnoNativeService` to expose functions needed by Gnokey Mobile (without changing functionality). This PR has two commits:
* In api.go, make `ConvertKeyInfo` a public helper function so that Gnokey Mobile can use it.
* In the `GnoNativeService` interface, add `ClientGetRemote`, `ClientListKeyInfo` and `ClientSignTx`. In `gnoNativeService`, implement these and update `GetRemote`, `ListKeyInfo` and `SignTx` to use them.
> chore: In `GnoNativeService` interface, add methods needed by Gnokey Mobile

- expo/src/api/GnoNativeApi.ts
- expo/src/api/types.ts
The previous PR added UpdatePassword to the gRPC API, but we also need to add it to GnoNativeApi so that it is available in the NPM provider. (This is a "fix" PR, so it should automatically upload a new NPM.)
> fix: In GnoNativeApi, add missing updatePassword

- expo/package-lock.json
- expo/src/api/GnoNativeApi.ts
This is a fix to PR #166 . We need to update @buf/gnolang_gnonative.bufbuild_es . In expo, I entered:
```
npm install @buf/gnolang_gnonative.bufbuild_es
npm install @buf/gnolang_gnonative.connectrpc_es
```
Now, `make npm.pack` succeeds, and Semantic Release should be able to upload the new NPM.
(This PR also fixes a typo in GnoNativeAPI.ts from PR #167 .)
> fix: In expo, update @buf/gnolang_gnonative.bufbuild_es

- service/api.go
- service/service.go
`gnoNativeService.userAccounts` is a map used to track all the user accounts which have been selected, including their password. Currently, the map key is either the [account name or the bech32 address](https://github.com/gnolang/gnonative/blob/44852235c93c78ff30680e16ec0665dddca987d8/service/api.go#L235). We want to rely on `gnoNativeService.userAccounts` where we only know the account address (not the name). For example, to sign a transaction with any key that has been selected, known only by its address. This PR standardizes the key of `gnoNativeService.userAccounts` to only be the bech32 address:
* In `SelectAccount`, store the account info in `gnoNativeService.userAccounts` using the bech32. (This is backwards compatible, even if the application calls `SelectAccount` to select by …
> chore: In gnoNativeService.userAccounts, use bech32 for the key

- go.mod
- go.sum
- service/api.go
Gno PR https://github.com/gnolang/gno/pull/2641 has been merged, so we don't need the go.mod replace which was introduced in PR https://github.com/gnolang/gnonative/pull/161 .
* In go.mod, remove the replace and use the latest gnolang/gno.
* The final gnoclient API which was merged in PR https://github.com/gnolang/gno/pull/2641 is different. It uses `vm.MsgCall`, etc. instead of `gnoclient.MsgCall`, and uses `NewCallTx`, etc. instead of `MakeCallTx`. Therefore, this PR updates api.go to use the new API.
* Change the helper functions `convertCallRequest`, etc. to maybe return an error if there is no active account, or if the `send` amount like "1000ugnot" can't be parsed.
> fix: Remove go.mod replace for gno. Use new gnoclient API.

- expo/package-lock.json
- expo/src/api/GnoNativeApi.ts
- expo/src/api/types.ts
- go.mod
- go.sum
PR https://github.com/gnolang/gnonative/pull/172 update the API to support using any activated account. We need to update the expo provider to the same API. This PR has 3 commits:
1. Update go.mod to use the latest gnokey-mobile following changes in PR https://github.com/gnolang/gnokey-mobile/pull/9
2. In expo, npm install the latest gnolang_gnonative.bufbuild_es and connectrpc_es to access the new API
3. Update expo/src/api/GnoNativeApi.ts to match the new API to use any activated account, specified by address. Note that the address parameters are optional for temporary backwards compatibility. When dSocial and Gnokey Mobile are updated to use the new API and specify the address, we will do a PR to require the address parameter, and to remove the deprecated `selectAccount` and …
> feat: Update expo to use any activated account

- expo/package-lock.json
- expo/package.json
This PR fixes an issue when you want to execute `npm install` in the `expo` folder, that fails with this error:
```bash
src/api/GnoNativeApi.ts:249:91 - error TS2561: Object literal may only specify known properties, but 'addresses' does not exist in type 'PartialMessage<UpdatePasswordRequest>'. Did you mean to write 'address'?
249     const response = await client.updatePassword(new UpdatePasswordRequest({ newPassword, addresses }));
```
It's because we need to update the `gnonative` API that implements the new addresses field in the request.
> fix: update gnonative API

- examples/js/expo/gnoboard/src/GoBridge/types.ts
- examples/js/expo/gnoboard/src/api/GnoNativeApi.ts
- examples/js/expo/gnoboard/src/api/types.ts
- examples/js/expo/gnoboard/src/screens/devmode/index.tsx
- examples/js/react-native/hello/GoBridge/types.ts
- examples/js/react-native/hello/api/GnoNativeApi.ts
- examples/js/react-native/hello/api/types.ts
- expo/src/api/GnoNativeApi.ts
- expo/src/api/types.ts
This PR adds MakeCallTx, SignTx and BroadcastTxCommit in GnoNativeApi. So the front can directly calls these methods now.
This PR also cleans the GnoNativeApi files, mostly by removing unnecessary `await` keywords.
BREAKING CHANGE: the gasWanted parameter (used in several gRPC message) is now a bigint instead of a number to keep the precision in the calling stack.
> BREAKING CHANGE: add MakeCallTx, SignTx and BroadcastTxCommit in GnoNativeApi

- examples/js/expo/gnoboard/Makefile
- examples/js/expo/gnoboard/package.json
- examples/js/expo/gnoboard/src/components/change-network/ChangeNetwork.stories.tsx
- examples/js/expo/gnoboard/src/components/common/side-menu-account-item/side-menu-account-item.tsx
- examples/js/expo/gnoboard/src/screens/devmode/index.tsx
- examples/js/expo/gnoboard/src/screens/switch-accounts/ReenterPassword.tsx
- examples/js/expo/gnoboard/src/screens/wallet/home/index.tsx
Similar to dSocial PR https://github.com/gnolang/dsocial/pull/132, we want to use `npm run ts:check` in the Makefile for gnoboard, but first we must resolve the errors. This PR has five commits:
1. Add ts:check to package.json
2. A [previous commit](https://github.com/gnolang/gnonative/commit/b5861145b5f58a15afb6886a3c33c031ad560975) changes gnoboard to use `KeyInfo` instead of the alias `GnoAccount` . It seems that this was missed in one file, so we make the same change.
3. In the catch clause, we call `GRPCError` which expects `ConnectError` or null. But the error in the catch can be any type. So add an explicit check for `instanceof ConnectError` .
4. The definition of `NetworkList` includes `onNetworkChange`, but ChangeNetwork.stories doesn't have it. However, `onNetworkChange` isn't …
> chore: gnoboard: Resolve ts:check errors, put in Makefile

- examples/js/expo/gnoboard/App.tsx
- examples/js/expo/gnoboard/Makefile
- examples/js/expo/gnoboard/src/provider/gnoboard-provider.tsx
- examples/js/expo/gnoboard/src/screens/certify/create-password/index.tsx
- examples/js/expo/gnoboard/src/screens/certify/enter-seed/index.tsx
- examples/js/expo/gnoboard/src/screens/devmode/index.tsx
- examples/js/expo/gnoboard/src/screens/switch-accounts/ReenterPassword.tsx
- examples/js/expo/gnoboard/src/screens/switch-accounts/index.tsx
- examples/js/expo/gnoboard/src/screens/wallet/home/index.tsx
Similar to PR https://github.com/gnolang/dsocial/pull/130, we update gnoboard to use the new Gno Native Kit API which removes `selectAccount` and requires passing the account address to `setPassword`, etc. This PR has five commits:
1. The app needs to keep track of the active account, so add `GnoboardProvider`.
2. Instead of calling Gno Native Kit `selectAccount`, call `GnoboardProvider` `setAccount` to remember the active account.
3. `setPassword` needs the account address, so in `ReenterPassword` add param `accountAddress`.
4. In wallet/home: Pass in the account instead of calling `getActiveAccount`. Use the account address to call `queryAccount`.
5. As in a [similar dsocial PR](https://github.com/gnolang/dsocial/pull/134), fix the Makefile to call ts_check after node_modules.
With this …
> chore: Remove getActiveAccount usage

- expo/package-lock.json
- expo/package.json
PR https://github.com/gnolang/gnonative/pull/184 did a BREAKING CHANGE to the API and created a new NPM package. Now we need to update expo/package-lock.json to use this for the bufbuild and connectrpc dependencies.
I used `make npm.pack` to create a local package and verified with dSocial builds with it.
> fix: expo: Update bufbuild and connectrpc dependencies to the latest NPM package

- expo/src/api/GnoNativeApi.ts
- expo/src/api/types.ts
In PR https://github.com/gnolang/gnonative/pull/188, we updated expo dependencies to use the new gnonative package with `RotatePassword`. In the expo TypeScript API, we also need to rename `updatePassword` to `rotatePassword`.
> fix: expo/api: Rename updatePassword to rotatePassword

- service/api.go
In gnoNativeService, `RotatePassword` calls `Lock` at the beginning of the function, then [calls `getSigner`](https://github.com/gnolang/gnonative/blob/cdd7bcbfc3b932396e3c469f65859b772d35d44a/service/api.go#L285) . But `getSigner` [calls `RLock`](https://github.com/gnolang/gnonative/blob/cdd7bcbfc3b932396e3c469f65859b772d35d44a/service/service.go#L193) which blocks, and `RotatePassword` never returns. (The effect is that Gnokey Mobile hangs during "Change Master Password".) This PR changes `RotatePassword` to call `Lock` after the loop which calls `getSigner`.
This was tested by doing `make npm.pack` and installing it locally in Gnokey Mobile.
> fix: gnoNativeService: In RotatePassword, call Lock() after getSigner

- go.mod
- go.sum
- service/api.go
PR https://github.com/gnolang/gno/pull/2910 moved `MemPackage` to the gnovm package. We want to track the latest gnolang/gno code. This PR updates to use the latest gnolang/gno and changes the reference of `MemPackage` to gnovm. After we merge this PR, we will update gnokey-mobile to use this latest gnonative, which is possible because gnokey-mobile no longer uses a replace for gnolang/gno.
> chore: Use the latest gnolang/gno. MemPackage is moved to gnovm

- api/gen/csharp/Gnonativetypes.cs
- api/gen/csharp/RpcGrpc.cs
- api/gen/es/gnonativetypes_pb.ts
- api/gen/es/rpc_connect.ts
- api/gen/go/_goconnect/rpc.connect.go
- api/gen/go/gnonativetypes.pb.go
- api/gnonativetypes.proto
- api/gnonativetypes/gnonativetypes.go
- gen.sum
- go.mod
- go.sum
- service/api.go
In goclient, the `ResultBroadcastTxCommit` contains the [transaction hash and height](https://github.com/gnolang/gno/blob/84abee0162e9253ef3bfa475f5b4b1fc5ef4f8c3/tm2/pkg/bft/rpc/core/types/responses.go#L160-L161). In Gno Key Mobile, we have a use case for showing the transaction hash. So update the gRPC types `CallResponse`, etc. to include the hash and height.
* In `gnonativetypes`, add `Hash` and `Height` to responses where possible
* Run `make regenerate`
* In the `gnoNativeService` API, put the `Hash` and `Height` in the response
Here is test code for [dSocial `broadcastTxCommit`](https://github.com/gnoverse/dsocial/blob/b25344b553bf350812052a9efe98f1db6e276848/mobile/redux/features/linkingSlice.ts#L99) .
```
for await (const res of await gnonative.broadcastTxCommit(signedTx)) { …
```
> chore: In responses, add Hash and Height

- expo/package-lock.json
- expo/package.json
- expo/src/provider/gnonative-provider.tsx
react-19 is used in Expo-53 (the latest), so we want to use it.
> chore: use react-19 in the expo-module

- examples/go/goclient/main.go
The goclient example call the Render function to show an example page. In the past, the default gnoland node had posts in the r/demo/boards realm. But it doesn't anymore. Change to r/gnoland/pages which does have content.
`go run . uds` shows:
```
2025/05/15 13:36:37 <main class='gno-tmpl-page'>
Are you a builder, tinkerer, or researcher? If you’re looking to create awesome dApps, tooling, infrastructure,
or smart contract libraries on gno.land, you can apply for a grant. The gno.land Ecosystem Fund and Grants program
provides financial contributions for individuals and teams to innovate on the platform.
...
```
> chore: goclient: Change to an active example page

- service/api.go
After the recent "crossing" changes, `TestRunSingle_Integration`, etc. were updated so that `std.MemPackage` [needs a `Name`](https://github.com/gnolang/gno/blob/9b763e9b11a55be644f33208840ad2e8f88336af/gno.land/pkg/gnoclient/integration_test.go#L340-L341) so that the back end handler can use it to set the `Path`. We need to do the same. Without this, calling `Run` results in an "invalid path" error.
> fix: convertRunRequest: std.MemPackage needs a Name

- expo/src/api/GnoNativeApi.ts
- expo/src/api/types.ts
In expo/src/api types.ts and GnoNativeApi.ts, add functions and optional params to bring expo up to date with the gRPC API:
* Add `run`, `makeRunTx` and `createLedger`
* In `createAccount`, add optional params `bip39Passwd`, `account` and `index` from [the gRPC API](https://github.com/gnolang/gnonative/blob/28ad53a4ef5bb5bb99b9eed29d72de59f256456b/api/gnonativetypes/gnonativetypes.go#L130-L133)
This PR only adds new functions and optional params. It should not break any existing code.
> feat: Bring expo up to date with gRPC API
